{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "city-finder.fullname" . }}
  labels:
    {{- include "city-finder.labels" . | nindent 4 }}
  annotations:
    {{- include "city-finder.syncWave" 0 | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "city-finder.selectorLabels" . | nindent 6 }}
{{- end }}
